# Generated by Django 3.1.7 on 2021-04-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
    ]
